//! Embed the negative-example corpus so `glyph --explain <CODE> --json` can
//! answer with a wrong program that draws the code.
//!
//! `tests/negative/` is the corpus `cargo test` already compiles and asserts
//! the code of, and it was visible to nothing else: the 41 wrong programs in it
//! were read by the test harness and by no agent (G222's C5, reached here
//! through G220). The table is generated rather than hand-listed so a case
//! added to the directory is in the answer with no second edit to remember.
//!
//! A case is one `.glyph` file beside a `.expected_error`, or a directory of
//! modules beside an `expected_error` when the case needs more than one module.
//!
//! `catches/` is embedded the same way and for the same reason. Each of its
//! directories is one program written twice: the TypeScript a `tsc --strict`
//! project accepts, and the Glyph that refuses it. That pairing is the evidence
//! behind every claim Glyph makes about catching what TypeScript does not, and
//! it was visible to `scripts/check_catches.py` and to nothing an agent can
//! run.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    // `CARGO_MANIFEST_DIR` is `<repo>/glyph-compiler/crates/glyph-cli`.
    let root: PathBuf = [env!("CARGO_MANIFEST_DIR"), "..", "..", "..", "tests", "negative"]
        .iter()
        .collect();
    println!("cargo:rerun-if-changed={}", root.display());

    let mut cases: Vec<Case> = Vec::new();
    if let Ok(entries) = std::fs::read_dir(&root) {
        let mut paths: Vec<PathBuf> = entries.filter_map(|e| e.ok().map(|e| e.path())).collect();
        paths.sort();
        for path in paths {
            if let Some(case) = read_case(&path) {
                cases.push(case);
            }
        }
    }

    let mut out = String::new();
    out.push_str(
        "/// One wrong program from `tests/negative/`, with the code it draws.\n\
         ///\n\
         /// Generated by `build.rs` from the directory itself, so the corpus a\n\
         /// release ships and the corpus `cargo test` runs are the same files.\n\
         pub struct NegativeCase {\n    \
             pub name: &'static str,\n    \
             /// The code its `expected_error` names.\n    \
             pub code: &'static str,\n    \
             /// `(file name, source)` per module, sorted.\n    \
             pub files: &'static [(&'static str, &'static str)],\n\
         }\n\n\
         /// Every case in the corpus, sorted by name.\n\
         pub static NEGATIVE_CASES: &[NegativeCase] = &[\n",
    );
    for case in &cases {
        let _ = write!(
            out,
            "    NegativeCase {{ name: {:?}, code: {:?}, files: &[",
            case.name, case.code
        );
        for (file, path) in &case.files {
            println!("cargo:rerun-if-changed={}", path.display());
            let _ = write!(out, "({file:?}, include_str!({:?})), ", path.display());
        }
        out.push_str("] },\n");
    }
    out.push_str("];\n");

    out.push_str(&catches_table());

    let dest = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR is set")).join("negative_cases.rs");
    std::fs::write(&dest, out).expect("write the generated corpus table");
}

/// The `catches/` corpus, generated the same way as `tests/negative/`.
fn catches_table() -> String {
    let root: PathBuf = [env!("CARGO_MANIFEST_DIR"), "..", "..", "..", "catches"]
        .iter()
        .collect();
    println!("cargo:rerun-if-changed={}", root.display());

    let mut dirs: Vec<PathBuf> = match std::fs::read_dir(&root) {
        Ok(entries) => entries
            .filter_map(|e| e.ok().map(|e| e.path()))
            .filter(|p| p.is_dir())
            .collect(),
        Err(_) => Vec::new(),
    };
    dirs.sort();

    let mut out = String::from(
        "\n/// One `catches/` case: a program TypeScript accepts and Glyph refuses.\n\
         ///\n\
         /// Generated by `build.rs` from the directory itself, so the corpus the\n\
         /// `check_catches.py` gate runs and the corpus a release ships are the\n\
         /// same files.\n\
         pub struct CatchCase {\n    \
             pub name: &'static str,\n    \
             /// The code its `case.toml` names.\n    \
             pub code: &'static str,\n    \
             /// The pillar the case is evidence for.\n    \
             pub pillar: &'static str,\n    \
             /// Its one-line title.\n    \
             pub title: &'static str,\n    \
             /// The TypeScript a `tsc --strict` project accepts.\n    \
             pub typescript: &'static str,\n    \
             /// `(file name, source)` per Glyph module, sorted.\n    \
             pub files: &'static [(&'static str, &'static str)],\n\
         }\n\n\
         /// Every case in the corpus, sorted by name.\n\
         pub static CATCH_CASES: &[CatchCase] = &[\n",
    );
    for dir in &dirs {
        let Some(case) = read_catch(dir) else {
            continue;
        };
        let _ = write!(
            out,
            "    CatchCase {{ name: {:?}, code: {:?}, pillar: {:?}, title: {:?}, typescript: include_str!({:?}), files: &[",
            case.name, case.code, case.pillar, case.title, case.typescript.display()
        );
        for (file, path) in &case.files {
            println!("cargo:rerun-if-changed={}", path.display());
            let _ = write!(out, "({file:?}, include_str!({:?})), ", path.display());
        }
        out.push_str("] },\n");
    }
    out.push_str("];\n");
    out
}

struct Catch {
    name: String,
    code: String,
    pillar: String,
    title: String,
    typescript: PathBuf,
    files: Vec<(String, PathBuf)>,
}

/// Read one `catches/` directory, or `None` when it is not a whole case.
fn read_catch(dir: &Path) -> Option<Catch> {
    let name = dir.file_name()?.to_string_lossy().into_owned();
    let meta_path = dir.join("case.toml");
    let meta = std::fs::read_to_string(&meta_path).ok()?;
    println!("cargo:rerun-if-changed={}", meta_path.display());
    // `case.toml` is three `key = "value"` lines and nothing else; the gate
    // script reads it with the same one-line rule.
    let field = |key: &str| -> Option<String> {
        meta.lines()
            .filter_map(|l| l.split_once('='))
            .find(|(k, _)| k.trim() == key)
            .map(|(_, v)| v.trim().trim_matches('"').to_string())
    };
    let code = field("code")?;
    if code.len() != 5 || !code.starts_with('E') {
        return None;
    }
    let typescript = dir.join("ts.ts");
    if !typescript.is_file() {
        return None;
    }
    println!("cargo:rerun-if-changed={}", typescript.display());
    let mut files: Vec<(String, PathBuf)> = std::fs::read_dir(dir)
        .ok()?
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("glyph"))
        .filter_map(|p| {
            let file = p.file_name()?.to_string_lossy().into_owned();
            Some((file, p))
        })
        .collect();
    files.sort();
    if files.is_empty() {
        return None;
    }
    Some(Catch {
        name,
        code,
        pillar: field("pillar").unwrap_or_default(),
        title: field("title").unwrap_or_default(),
        typescript,
        files,
    })
}

struct Case {
    name: String,
    code: String,
    /// `(file name, absolute path)` per module, sorted by file name.
    files: Vec<(String, PathBuf)>,
}

/// Read one corpus entry, or `None` when the path is neither half of a case.
fn read_case(path: &Path) -> Option<Case> {
    let name = path.file_stem()?.to_string_lossy().into_owned();
    let (expected, files) = if path.is_dir() {
        let mut modules: Vec<(String, PathBuf)> = std::fs::read_dir(path)
            .ok()?
            .filter_map(|e| e.ok().map(|e| e.path()))
            .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("glyph"))
            .filter_map(|p| {
                let file = p.file_name()?.to_string_lossy().into_owned();
                Some((file, p))
            })
            .collect();
        modules.sort();
        if modules.is_empty() {
            return None;
        }
        (path.join("expected_error"), modules)
    } else {
        if path.extension().and_then(|e| e.to_str()) != Some("glyph") {
            return None;
        }
        let file = path.file_name()?.to_string_lossy().into_owned();
        (path.with_extension("expected_error"), vec![(file, path.to_path_buf())])
    };
    let code = std::fs::read_to_string(&expected).ok()?.trim().to_string();
    if code.len() != 5 || !code.starts_with('E') {
        return None;
    }
    println!("cargo:rerun-if-changed={}", expected.display());
    Some(Case { name, code, files })
}
