//! Embed the negative-example corpus so `glyph --explain <CODE> --json` can
//! answer with a wrong program that draws the code.
//!
//! `tests/negative/` is the corpus `cargo test` already compiles and asserts
//! the code of, and it was visible to nothing else: the 41 wrong programs in it
//! were read by the test harness and by no agent (G222's C5, reached here
//! through G220). The table is generated rather than hand-listed so a case
//! added to the directory is in the answer with no second edit to remember.
//!
//! A case is one `.glyph` file beside a `.expected_error`, or a directory of
//! modules beside an `expected_error` when the case needs more than one module.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    // `CARGO_MANIFEST_DIR` is `<repo>/glyph-compiler/crates/glyph-cli`.
    let root: PathBuf = [env!("CARGO_MANIFEST_DIR"), "..", "..", "..", "tests", "negative"]
        .iter()
        .collect();
    println!("cargo:rerun-if-changed={}", root.display());

    let mut cases: Vec<Case> = Vec::new();
    if let Ok(entries) = std::fs::read_dir(&root) {
        let mut paths: Vec<PathBuf> = entries.filter_map(|e| e.ok().map(|e| e.path())).collect();
        paths.sort();
        for path in paths {
            if let Some(case) = read_case(&path) {
                cases.push(case);
            }
        }
    }

    let mut out = String::new();
    out.push_str(
        "/// One wrong program from `tests/negative/`, with the code it draws.\n\
         ///\n\
         /// Generated by `build.rs` from the directory itself, so the corpus a\n\
         /// release ships and the corpus `cargo test` runs are the same files.\n\
         pub struct NegativeCase {\n    \
             pub name: &'static str,\n    \
             /// The code its `expected_error` names.\n    \
             pub code: &'static str,\n    \
             /// `(file name, source)` per module, sorted.\n    \
             pub files: &'static [(&'static str, &'static str)],\n\
         }\n\n\
         /// Every case in the corpus, sorted by name.\n\
         pub static NEGATIVE_CASES: &[NegativeCase] = &[\n",
    );
    for case in &cases {
        let _ = write!(
            out,
            "    NegativeCase {{ name: {:?}, code: {:?}, files: &[",
            case.name, case.code
        );
        for (file, path) in &case.files {
            println!("cargo:rerun-if-changed={}", path.display());
            let _ = write!(out, "({file:?}, include_str!({:?})), ", path.display());
        }
        out.push_str("] },\n");
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR is set")).join("negative_cases.rs");
    std::fs::write(&dest, out).expect("write the generated corpus table");
}

struct Case {
    name: String,
    code: String,
    /// `(file name, absolute path)` per module, sorted by file name.
    files: Vec<(String, PathBuf)>,
}

/// Read one corpus entry, or `None` when the path is neither half of a case.
fn read_case(path: &Path) -> Option<Case> {
    let name = path.file_stem()?.to_string_lossy().into_owned();
    let (expected, files) = if path.is_dir() {
        let mut modules: Vec<(String, PathBuf)> = std::fs::read_dir(path)
            .ok()?
            .filter_map(|e| e.ok().map(|e| e.path()))
            .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("glyph"))
            .filter_map(|p| {
                let file = p.file_name()?.to_string_lossy().into_owned();
                Some((file, p))
            })
            .collect();
        modules.sort();
        if modules.is_empty() {
            return None;
        }
        (path.join("expected_error"), modules)
    } else {
        if path.extension().and_then(|e| e.to_str()) != Some("glyph") {
            return None;
        }
        let file = path.file_name()?.to_string_lossy().into_owned();
        (path.with_extension("expected_error"), vec![(file, path.to_path_buf())])
    };
    let code = std::fs::read_to_string(&expected).ok()?.trim().to_string();
    if code.len() != 5 || !code.starts_with('E') {
        return None;
    }
    println!("cargo:rerun-if-changed={}", expected.display());
    Some(Case { name, code, files })
}
